name: Test Workflow

on:
  push:
    branches: [main]

jobs:
  GITHUBSTATEANDOUTPUTTEST:
    name: Test GITHUBSTATE and OUTPUT env vars
    runs_on: ubuntu:latest
    steps: 
      - name: Save GITHUB_STATE
        run: |
          echo "{name}={value}" >> $GITHUB_STATE
      - name: Output STATE
        run: |
          echo $GITHUB_STATE
    
